### ISSUE TITLE
Failing Expressions in Linq2db

### ISSUE THREAD

**Issue by jogibear9988** [dadhi/FastExpressionCompiler#283]
Test: PostgreSQLTests.TestExtraTypesBulkCopy
Exception: OverflowException

	var p = new ParameterExpression[10]; // the parameter expressions 
	var e = new Expression[23]; // the unique expressions 
	var l = new LabelTarget[0]; // the labels 
	var expr = Lambda( // $
	  typeof(System.Func<LinqToDB.Linq.IQueryRunner, System.Data.IDataReader, Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable>),
	  e[0]=Invoke(
		e[1]=Lambda( // $
		  typeof(System.Func<LinqToDB.Linq.IQueryRunner, LinqToDB.IDataContext, System.Data.IDataReader, System.Linq.Expressions.Expression, object[], object[], Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable>),
		  e[2]=Block(
			typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable),
			new[] {
			p[0]=Parameter(typeof(Npgsql.NpgsqlDefaultDataReader), "ldr"),
			p[1]=Parameter(typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable), "ExtraBulkCopyTypesTable1")
			},
			e[3]=MakeBinary(ExpressionType.Assign,
			  p[0 // (Npgsql.NpgsqlDefaultDataReader ldr)
				],
			  e[4]=Convert(
				p[2]=Parameter(typeof(System.Data.IDataReader), "dr"),
				typeof(Npgsql.NpgsqlDefaultDataReader))), 
			e[5]=MakeBinary(ExpressionType.Assign,
			  p[1 // (Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable ExtraBulkCopyTypesTable1)
				],
			  e[6]=Convert(
				e[7]=Call(
				  null, 
				  typeof(LinqToDB.Linq.Builder.TableBuilder.TableContext).GetMethods(BindingFlags.NonPublic|BindingFlags.Static).Single(x => !x.IsGenericMethod && x.Name == "OnEntityCreated" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(LinqToDB.IDataContext), typeof(object) })),
				  p[3]=Parameter(typeof(LinqToDB.IDataContext), "dctx"), 
				  e[8]=MemberInit(
					e[9]=New(/*0 args*/
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().DeclaredConstructors.ToArray()[0], new Expression[0]), 
					Bind(
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().GetDeclaredProperty("Id"), 
					  e[10]=
						// NOT_SUPPORTED_EXPRESSION: Extension
						), 
					Bind(
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().GetDeclaredProperty("Byte"), 
					  e[11]=
						// NOT_SUPPORTED_EXPRESSION: Extension
						), 
					Bind(
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().GetDeclaredProperty("SByte"), 
					  e[12]=
						// NOT_SUPPORTED_EXPRESSION: Extension
						), 
					Bind(
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().GetDeclaredProperty("Int16"), 
					  e[13]=
						// NOT_SUPPORTED_EXPRESSION: Extension
						), 
					Bind(
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().GetDeclaredProperty("UInt16"), 
					  e[14]=
						// NOT_SUPPORTED_EXPRESSION: Extension
						), 
					Bind(
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().GetDeclaredProperty("Int32"), 
					  e[15]=
						// NOT_SUPPORTED_EXPRESSION: Extension
						), 
					Bind(
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().GetDeclaredProperty("UInt32"), 
					  e[16]=
						// NOT_SUPPORTED_EXPRESSION: Extension
						), 
					Bind(
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().GetDeclaredProperty("Int64"), 
					  e[17]=
						// NOT_SUPPORTED_EXPRESSION: Extension
						), 
					Bind(
					  typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable).GetTypeInfo().GetDeclaredProperty("UInt64"), 
					  e[18]=
						// NOT_SUPPORTED_EXPRESSION: Extension
						))),
				typeof(Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable))), 
			p[1 // (Tests.DataProvider.PostgreSQLTests.ExtraBulkCopyTypesTable ExtraBulkCopyTypesTable1)
			  ]),
		  p[4]=Parameter(typeof(LinqToDB.Linq.IQueryRunner), "qr"), 
		  p[3 // (LinqToDB.IDataContext dctx)
			], 
		  p[5]=Parameter(typeof(System.Data.IDataReader), "rd"), 
		  p[6]=Parameter(typeof(System.Linq.Expressions.Expression), "expr"), 
		  p[7]=Parameter(typeof(object[]), "ps"), 
		  p[8]=Parameter(typeof(object[]), "preamble")),
		p[9]=Parameter(typeof(LinqToDB.Linq.IQueryRunner), "qr"), 
		e[19]=Property(
		  p[9 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("DataContext")), 
		p[2 // (System.Data.IDataReader dr)
		  ], 
		e[20]=Property(
		  p[9 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("Expression")), 
		e[21]=Property(
		  p[9 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("Parameters")), 
		e[22]=Property(
		  p[9 // (LinqToDB.Linq.IQueryRunner qr)
			],
		  typeof(LinqToDB.Linq.IQueryRunner).GetTypeInfo().GetDeclaredProperty("Preambles"))),
	  p[9 // (LinqToDB.Linq.IQueryRunner qr)
		], 
	  p[2 // (System.Data.IDataReader dr)
		]);

**Comment by dadhi** [comment]
@jogibear9988 Thanks.
How many tests are still failing?
Is the number going down?

**Comment by jogibear9988** [comment]
I think it's going down...
Problem is, Linq2db Test Pipeline seems also have some issues with running agains master branch at the moment.
So I have to run the test's on my system, but there do not work all of them.
I only found this issue at the moment (wich works if I switch back to default expression compiler)

**Comment by jogibear9988** [comment]
sorry, but this one is still not fixed:

https://github.com/dadhi/FastExpressionCompiler/issues/274#issuecomment-720705244

**Comment by jogibear9988** [comment]
Found one more:

Test: MapHasFlag.MapHasFlag
Exception: NullRefException

	var p = new ParameterExpression[3]; // the parameter expressions 
	var e = new Expression[23]; // the unique expressions 
	var l = new LabelTarget[0]; // the labels 
	var expr = Lambda( // $
	  typeof(System.Func<System.Linq.Expressions.Expression, LinqToDB.IDataContext, object[], object>),
	  e[0]=Convert(
		e[1]=Call(
		  null, 
		  typeof(LinqToDB.Sql.ConvertTo<int>).GetMethods().Where(x => x.IsGenericMethod && x.Name == "From" && x.GetGenericArguments().Length == 1).Select(x => x.IsGenericMethodDefinition ? x.MakeGenericMethod(typeof(System.Enum)) : x).Single(x => x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(System.Enum) })),
		  e[2]=Convert(
			e[3]=Field(
			  e[4]=Convert(
				e[5]=Property(
				  e[6]=Convert(
					e[7]=Property(
					  e[8]=Convert(
						e[9]=Property(
						  e[10]=Convert(
							e[11]=Call(
							  e[12]=Property(
								e[13]=Convert(
								  e[14]=Property(
									e[15]=Convert(
									  e[16]=Property(
										e[17]=Convert(
										  e[18]=Call(
											e[19]=Property(
											  e[20]=Convert(
												p[0]=Parameter(typeof(System.Linq.Expressions.Expression), "expr"),
												typeof(System.Linq.Expressions.MethodCallExpression)),
											  typeof(System.Linq.Expressions.MethodCallExpression).GetTypeInfo().GetDeclaredProperty("Arguments")), 
											typeof(System.Collections.ObjectModel.ReadOnlyCollection<System.Linq.Expressions.Expression>).GetMethods().Single(x => !x.IsGenericMethod && x.Name == "get_Item" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(int) })),
											e[21]=Constant((int)1)),
										  typeof(System.Linq.Expressions.UnaryExpression)),
										typeof(System.Linq.Expressions.UnaryExpression).GetTypeInfo().GetDeclaredProperty("Operand")),
									  typeof(System.Linq.Expressions.LambdaExpression)),
									typeof(System.Linq.Expressions.LambdaExpression).GetTypeInfo().GetDeclaredProperty("Body")),
								  typeof(System.Linq.Expressions.MethodCallExpression)),
								typeof(System.Linq.Expressions.MethodCallExpression).GetTypeInfo().GetDeclaredProperty("Arguments")), 
							  typeof(System.Collections.ObjectModel.ReadOnlyCollection<System.Linq.Expressions.Expression>).GetMethods().Single(x => !x.IsGenericMethod && x.Name == "get_Item" && x.GetParameters().Select(y => y.ParameterType).SequenceEqual(new[] { typeof(int) })),
							  e[22]=Constant((int)0)),
							typeof(System.Linq.Expressions.UnaryExpression)),
						  typeof(System.Linq.Expressions.UnaryExpression).GetTypeInfo().GetDeclaredProperty("Operand")),
						typeof(System.Linq.Expressions.MemberExpression)),
					  typeof(System.Linq.Expressions.MemberExpression).GetTypeInfo().GetDeclaredProperty("Expression")),
					typeof(System.Linq.Expressions.ConstantExpression)),
				  typeof(System.Linq.Expressions.ConstantExpression).GetTypeInfo().GetDeclaredProperty("Value")),
				typeof(Tests.Linq.ExpressionsTests.c__DisplayClass6_0)),
			  typeof(Tests.Linq.ExpressionsTests.c__DisplayClass6_0).GetTypeInfo().GetDeclaredField("flag")),
			typeof(System.Enum))),
		typeof(object)),
	  p[0 // (System.Linq.Expressions.Expression expr)
		], 
	  p[1]=Parameter(typeof(LinqToDB.IDataContext), "dctx"), 
	  p[2]=Parameter(typeof(object[]), "ps"));

**Comment by dadhi** [comment]
> it affects 8 tests (or more)

Good.. (this is a short one and something general) and I have already the test for this.
 
Actually there is a bunch of delegates passed there, but I did tested them all set to null. 
Likely the next step is to try with empty delegates.. Moreover I may output them as empty in the `ToExpressionString()`, don't know.

**Comment by dadhi** [comment]
@jogibear9988 

> Test: PostgreSQLTests.TestExtraTypesBulkCopy Exception: OverflowException

Regarding the first test, a see that it uses `// NOT_SUPPORTED_EXPRESSION: Extension`. So it is a question of how to deal with it first. 
1. I may ignore the `Extension` while compiling the expression, I believe that the System Compile does the same, and the Extension is used mainly to inject metadata into expression and then discover it using Visitor or similar traversing methods.
2. I may fallback to System Compile **which is the current behavior**

**Comment by jogibear9988** [comment]
I think 1. would be better...

butt I don‘t know what you mean with Extension...

**Comment by dadhi** [comment]
@jogibear9988 Here 
https://nejcskofic.github.io/2017/07/30/extending-linq-expressions/

**Comment by jogibear9988** [comment]
I thought the MS compiler calls Reduce to get the simpler Expression Representation

**Comment by dadhi** [comment]
@jogibear9988 I am still unable to reproduce the https://github.com/dadhi/FastExpressionCompiler/commit/57ece796fca3982174fee9e13472baf3ba2cbe2b
It is likely that something was lost in translation, could you please try to extract the expression again (hopefully I've fixed a number of extraction bugs later).

> I thought the MS compiler calls Reduce to get the simpler Expression Representation
You mean the Extension is being reduced? - yeah, very likely. I did not do a reduction mechanism in FEC because I don't a much win in it considering the complexity. I would rather just skip extension while compiling.

**Comment by dadhi** [comment]
> I thought the MS compiler calls Reduce to get the simpler Expression Representation

Ok, found that I am calling the Reduce already for Extension. Let's see.

**Comment by jogibear9988** [comment]
https://github.com/linq2db/linq2db/blob/ffed64756a5256f755fadc1c20cbaa05cc6eeb85/Source/LinqToDB/Expressions/DefaultValueExpression.cs#L24

**Comment by jogibear9988** [comment]
You didn't change anything since I extracted the method at last.
Maybe you can run that test yourself? This one does not use a database.

**Comment by dadhi** [comment]
@jogibear9988 ok, will try

**Comment by dadhi** [comment]
> I thought the MS compiler calls Reduce to get the simpler Expression Representation

I have changed FEC to output the reduced Extension in `ToExpressionString` and in the `ToCSharpString`

**Comment by dadhi** [comment]
@jogibear9988 I have released the V3-preview-06 with reducing the Extension so case 1 here can be extracted properly and with the fix (hopefully) for the `Test: MapHasFlag.MapHasFlag`.
If you can run it, then please.

**Comment by jogibear9988** [comment]
MappingTest.TesCollection still fails:

	var p = new ParameterExpression[2]; // the parameter expressions 
	var e = new Expression[6]; // the unique expressions 
	var l = new LabelTarget[0]; // the labels 
	var expr = Lambda( // $
	  typeof(System.Func<object, object>),
	  e[0]=Block(
		typeof(Tests.TypeMapping.Wrappers.SampleClass),
		new[] {
		p[0]=Parameter(typeof(Tests.TypeMapping.Wrappers.SampleClass))
		},
		e[1]=MakeBinary(ExpressionType.Assign,
		  p[0 // (Tests.TypeMapping.Wrappers.SampleClass sampleclass__63059985)
			],
		  e[2]=New(/*2 args*/
			typeof(Tests.TypeMapping.Wrappers.SampleClass).GetTypeInfo().DeclaredConstructors.ToArray()[0],
			p[1]=Parameter(typeof(object)), 
			e[3]=Constant(null, typeof(System.Delegate[])
			  // !!! Please provide the non-default value
			  ))), 
		e[4]=Invoke(
		  e[5]=Constant(null, typeof(System.Action<Tests.TypeMapping.Wrappers.SampleClass>)
			// !!! Please provide the non-default value
			),
		  p[0 // (Tests.TypeMapping.Wrappers.SampleClass sampleclass__63059985)
			]), 
		p[0 // (Tests.TypeMapping.Wrappers.SampleClass sampleclass__63059985)
		  ]),
	  p[1 // (object object__23780681)
		]);

**Comment by jogibear9988** [comment]
MapHasFlag works

**Comment by dadhi** [comment]
> MappingTest.TesCollection still fails

I did not worked with it yet.

**Comment by jogibear9988** [comment]
@dadhi  InvalidCast is still not fixed

**Comment by dadhi** [comment]
@jogibear9988 

> InvalidCast is still not fixed

You mean `MappingTests.TesCollection` ?

Strange, I run the test recently and it was passing.. Maybe it fails on the specific target. Will recheck.

**Comment by jogibear9988** [comment]
i've created a new issue.
